version: 2.1
orbs:
  ecspresso: fujiwara/ecspresso@0

jobs:
  shell_debian:
    docker:
      - image: debian:buster-slim
    steps:
      - ecspresso/install
      - run:
          command: |
            ecspresso --version


workflows:
  version: 2
  test_shell:
    jobs:
      - shell_debian
