version: 2.1
orbs:
  aws-cli-v2:
    commands:
      install:
        steps:
          - run: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
jobs:
  build:
    docker:
      - image: alpine:3.9
    steps:
      - run: |
          apk --no-cache add curl unzip
      - aws-cli-v2/install
      - run: |
          aws --version

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
