version: 2.1
orbs:
  ecspresso: fujiwara/ecspresso@dev:latest

jobs:
  shell_debian:
    docker:
      - image: circleci/golang:1.13.5
    steps:
      - ecspresso/install
      - run:
          command: |
            ecspresso --version


workflows:
  version: 2
  test_shell:
    jobs:
      - shell_debian
