version: 2.1

jobs:
  shell_circleci_golang:
    docker:
      - image: circleci/golang:1.12.9
    steps: &steps_for_shell
      - run:
          command: |
            echo "SHELL=$SHELL"
            echo -n "CURRENT SHELL"
            readlink /proc/$$/exe
            ps auxwf
  shell_alpine:
    docker:
      - image: alpine:3.9
    steps: *steps_for_shell

workflows:
  version: 2
  test_shell:
    jobs:
      - shell_circleci_golang
      - shell_alpine
