name: test
on: [push]
jobs:
  test:
    name: test-job
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: show env
      run: |
        env | sort
